### ISSUE TITLE
does not seem to work with Undertale

### ISSUE THREAD

**Issue by raingloom** [dotfloat/steam-appmanifest#11]
I searched this script just for this game, I haven't yet tested it with anything else.
When I restarted Steam it told me Undertale has finished installation, then when I tried starting it, it just gave the usual error about platform incompatibility.

The downloader reports "0 bytes / 0 bytes"

**Comment by raingloom** [comment]
tested with Sniper Elite v2, it works with that

**Comment by dotfloat** [comment]
This is a known issue when installing using this method. My guess is that the problem lies with that there exist both Windows and OS X versions of that game, so Steam doesn't know which one to download.

You can try going the SteamCMD route. I've been meaning to streamline it, but haven't gotten to it as of yet. So you're stuck with using the terminal for now.

Follow the Linux section of how to download SteamCMD on Valve's wiki: https://developer.valvesoftware.com/wiki/SteamCMD#Linux

Once it's done, run

    $ ./steamcmd.sh +@sSteamCmdForcePlatformType windows +login YOUR_STEAM_USERNAME +force_install_dir ./undertale +app_update 391540 +quit

Steam doesn't need to be restarted when using this method.

You can rerun this command to update the game in the future.

---

`+@sSteamCmdForcePlatformType windows` - The magic. Tells SteamCMD to download the Windows version. Presumably this is to allow Linux users to download Windows-only dedicated servers to run with wine.

`+login YOUR_STEAM_USERNAME` - SteamCMD uses the normal Steam installation directory, so if you've logged in with Steam before, then SteamCMD will be able to automatically log in using the provided account name. **If you haven't used Steam before on your machine, you'll need to follow the guide on how to log in, which can be found on the wiki page I linked to earlier.**

`+force_install_dir ./undertale` - Tells SteamCMD to download files to a (new) directory called `undertale`. Change it to whatever you wish.

`+app_update 391540` - Tells SteamCMD which Steam App it needs to download. `391540` is Undertale's AppID, which I found using [steamdb.info](http://steamdb.info).

`+quit` - Avoids starting the awful SteamCMD shell.

**Comment by raingloom** [comment]
Ah, thanks a lot!
Could you reference this somehow in the readme in case someone has the same problem?
